# Generated by Django 4.0 on 2022-01-01 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banzuke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('basho_location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rikishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('real_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.IntegerField()),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
            ],
        ),
        migrations.CreateModel(
            name='Shikona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shikona', models.CharField(max_length=200)),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rikishi')),
            ],
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rikishi')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(max_length=100)),
                ('rank_number', models.IntegerField()),
                ('rank_direction', models.CharField(max_length=50)),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rikishi')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rikishi')),
            ],
        ),
        migrations.CreateModel(
            name='Heya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heya_name', models.CharField(max_length=200)),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.rikishi')),
            ],
        ),
    ]
